# Generated by Django 4.2.1 on 2024-11-21 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ControllerManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
                ("num_visible_hosts", models.IntegerField(blank=True, default=1)),
                ("data", models.TextField(unique=True)),
                ("time_create", models.DateTimeField(auto_now_add=True)),
                ("time_update", models.DateTimeField(auto_now=True)),
                ("category", models.IntegerField()),
                ("user_name", models.CharField(default="0", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="SaveConfigFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=20)),
                (
                    "file",
                    models.FileField(
                        null=True,
                        upload_to="conflicts/configs/",
                        verbose_name="config_file",
                    ),
                ),
                (
                    "time_create",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "controller_type",
                    models.CharField(db_index=True, default="undefind", max_length=20),
                ),
                ("description", models.TextField(null=True)),
                ("number", models.CharField(max_length=100, null=True)),
                ("ip_adress", models.CharField(max_length=20, null=True)),
                ("adress", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SaveConflictsTXT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=20)),
                (
                    "file",
                    models.FileField(
                        null=True, upload_to="conflicts/txt/", verbose_name="txt_files"
                    ),
                ),
                ("time_create", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TelegrammUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_id", models.CharField(max_length=10, unique=True)),
                ("username", models.CharField(max_length=40, null=True)),
                ("first_name", models.CharField(max_length=40, null=True)),
                ("last_name", models.CharField(max_length=40, null=True)),
                ("access_level", models.IntegerField(default=0)),
                ("time_create", models.DateTimeField(auto_now_add=True)),
                ("time_update", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TrafficLightsObjects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField(null=True)),
                ("type_controller", models.CharField(max_length=20)),
                ("group", models.IntegerField(default=0)),
                ("ip_adress", models.CharField(max_length=20, null=True)),
                ("adress", models.TextField(blank=True, null=True)),
                ("time_create", models.DateTimeField(auto_now_add=True)),
                ("time_update", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
