# Generated by Django 4.2.1 on 2024-11-21 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("toolkit", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trafficlightsobjects",
            old_name="adress",
            new_name="address",
        ),
    ]
