# Generated by Django 4.2.1 on 2024-11-21 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("toolkit", "0002_rename_adress_trafficlightsobjects_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="saveconfigfiles",
            old_name="adress",
            new_name="address",
        ),
    ]
