# Generated by Django 4.2.1 on 2024-12-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toolkit", "0003_rename_adress_saveconfigfiles_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrafficLightConfigurator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "function",
                    models.CharField(max_length=255, verbose_name="Тип запроса"),
                ),
                ("condition_string", models.TextField(verbose_name="Условие из tlc")),
                (
                    "function_values",
                    models.TextField(
                        default="", max_length=255, verbose_name="Значения функций"
                    ),
                ),
                (
                    "condition_string_for_parse",
                    models.TextField(
                        default="",
                        verbose_name="Условие с заданными значениями функций",
                    ),
                ),
                (
                    "tokens",
                    models.TextField(
                        default="",
                        max_length=255,
                        verbose_name="Функции(токены) из условия tlc",
                    ),
                ),
                (
                    "result_condition_value",
                    models.BooleanField(
                        default="",
                        null=True,
                        verbose_name="Результат выражения условия из tlc для заданных функций",
                    ),
                ),
                ("errors", models.CharField(max_length=255, verbose_name="Ошибки")),
                (
                    "time_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
            ],
        ),
    ]
