# Generated by Django 4.2.1 on 2025-01-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toolkit", "0004_trafficlightconfigurator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saveconfigfiles",
            name="controller_type",
            field=models.CharField(db_index=True, default="undefined", max_length=20),
        ),
    ]
