# Generated by Django 4.2.1 on 2025-04-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toolkit", "0005_alter_saveconfigfiles_controller_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ControllerManagementOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_controller", models.CharField(max_length=20, unique=True)),
                ("group", models.IntegerField(default=0, unique=True)),
                ("commands", models.CharField(max_length=40)),
                ("max_stage", models.IntegerField()),
                ("options", models.CharField(max_length=255)),
                ("sources", models.CharField(max_length=255)),
            ],
        ),
    ]
