# Generated by Django 4.2.1 on 2025-04-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toolkit", "0006_controllermanagementoptions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="controllermanagementoptions",
            name="options",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
