# Generated by Django 4.2.1 on 2025-04-28 09:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("toolkit", "0007_alter_controllermanagementoptions_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="controllermanagementoptions",
            name="time_create",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="controllermanagementoptions",
            name="time_update",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
