# Generated by Django 4.2.1 on 2025-04-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toolkit", "0008_controllermanagementoptions_time_create_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="controllermanagementoptions",
            name="sources",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
